metadata.format.version = "1.1"

[versions]

configurate = "4.1.2"
runpaper = "2.3.1"
paper = "1.21-R0.1-SNAPSHOT"

[libraries]

configurate = { group = "org.spongepowered", name = "configurate-hocon", version.ref = "configurate" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
adventure-serializer = { group = "net.kyori", name = "adventure-serializer-configurate4", version = "4.18.0"}

[plugins]

runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "runpaper" }
